# H2 Veritabanı Ayarları
spring.datasource.url=jdbc:h2:mem:izin_personel_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Konsol Ayarları
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA / Hibernate Ayarları (Hata almamak için şimdilik update yapıyoruz)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Liquibase Ayarları
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml