spring.application.name=izin_personel_yonetimi

# H2 Veritabanı Ayarları
spring.datasource.url=jdbc:h2:mem:izin_personel_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Konsolu ve Hibernate Ayarları
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true